### ISSUE TITLE
Haanga.org appears to be something else

### ISSUE THREAD

**Issue by mikegioia** [crodas/Haanga#31]
I think your web domain may have expired and was picked up by another company.

**Comment by RamonZoocha** [comment]
That's a shame, because Haanga is so good and so light. It should be the most popular templating engine for PHP.

**Comment by RamonZoocha** [comment]
Correct, I think this is a great library and needs more maketing.

**Comment by crodas** [comment]
Indeed. I will focus on rewriting it to a more modern implementation.
